simplemooc/simplemooc/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from simplemooc.core import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^contato/$', views.contact, name='contact'),
]

simplemooc/simplemooc/courses/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from simplemooc.courses import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	# url(r'^(?P<pk>\d+)/$', views.details, name='details'),
	url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
]

simplemooc/simplemooc/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from simplemooc.core import views

urlpatterns = [
	url(r'^', include('simplemooc.core.urls', namespace='core')),
	url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
	url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

simplemooc/simplemooc/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
	return render(request, 'home.html')


def contact(request):
	return render(request, 'contact.html')

simplemooc/simplemooc/core/templates/core/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
        </ul>
    </div>
</div>
<div class="content">
    {% block content %}{% endblock %}
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>